format:
  mc: '&f[&bTG&f]&7 %player%&f: %message%'
  telegram: '[TG] <b>%player%</b>: %message%'
  telegram-escape-message: true

messages:
  join-leave: true
  death: true
  chat: true
  broadcast: true
token: ''