name: ${artifactId}
main: ${groupId}.${artifactId}
version: ${version}

authors: [Ecconia, Linus122]
description: Connects Telegram with your server chat.

commands:
   telegram:
      description: Register bot-token, link account, reload plugin, check connection.
