name: ${artifactId}
main: ${groupId}.${artifactId}
version: ${version}

authors: [Ecconia, Linus122]
description: Connects Telegram with your server chat.

commands:
   telegram:
      description: Register the bot or link your account
      usage: '§cUsage: /<command> <bot|link>'
      permission: telegram.setbot;telegram.link
