name: ${artifactId}
main: ${groupId}.${artifactId}Plugin
version: ${version}

authors: [Linus122]
description: Brings minecraft chat to Telegram!

commands:
   telegram:
      description: Main command
      usage: /<command> [token]
      permission: telegram.settoken
   linktelegram:
      description: Main command
      usage: /<command>
      permission: telegram.linktelegram