name: ${artifactId}
main: ${groupId}.${artifactId}Plugin
version: ${version}

authors: [Linus122]
description: Brings minecraft chat to Telegram!

commands:
   telegram:
      description: Register the bot
      usage: /<command> <token>
      permission: telegram.settoken

   linktelegram:
      description: Get your chat token
      usage: /<command>
      permission: telegram.linktelegram