name: ${artifactId}
main: ${groupId}.${artifactId}Plugin
version: ${version}

authors: [Linus122, Ecconia]
description: Connect Telegram with your server chat!

commands:
   telegram:
      description: Register the bot or link your account
      usage: '§cUsage: /<command> <bot|link>'
      permission: telegram.setbot;telegram.link
